### ISSUE TITLE
Изучить примеры BI в части поиска аномалий для веб-приложений

### ISSUE THREAD

**Issue by FomenkoKS** [NovatekTeam/FishResearch#4]

**Comment by Anna-Stakhova** [comment]
1.  D3:   https://d3js.org/
- Peak Detection for Data Visualization:    https://observablehq.com/@yurivish/peak-detection
- https://observablehq.com/@observablehq/plot-cell
- https://observablehq.com/@hepplerj/global-surface-temperature-anomalies
- https://observablehq.com/@d3/box-plot
- https://observablehq.com/@d3/brushable-scatterplot-matrix
- https://observablehq.com/@d3/multi-line-chart
- https://observablehq.com/@d3/difference-chart
- https://observablehq.com/@d3/dot-plot
- https://observablehq.com/@d3/line-with-tooltip

2. https://www.highcharts.com/
- https://www.highcharts.com/demo/annotations
- https://www.highcharts.com/demo/scatter
- https://www.highcharts.com/demo/heatmap-canvas
- https://www.highcharts.com/demo/bellcurve
- https://www.highcharts.com/demo/polygon
- https://www.highcharts.com/demo/polar-spider
- https://www.highcharts.com/demo/line-time-series
- https://www.highcharts.com/demo/heatmap
- https://www.highcharts.com/demo/stock/intraday-candlestick

3. https://www.amcharts.com/javascript-charts/
  https://www.amcharts.com/demos/#xy-bubble

4. https://canvasjs.com/

НО! мне кажется, прикольнее прикрутить супер сет, и потом в качестве презентации сделать а-ля сторителлинг по данным
